// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroLogin.DAL;

namespace RegistroLogin.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211107192028_MigracionUsuario")]
    partial class MigracionUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RegistroLogin.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Activo = true,
                            Alias = "Joselito",
                            Clave = "7110EDA4D09E062AA5E4A390B0A572AC0D2C0220",
                            Email = "josemanuel@gmail.com",
                            FechaIngreso = new DateTime(2021, 11, 7, 15, 20, 27, 538, DateTimeKind.Local).AddTicks(4814),
                            Nombres = "Para usuarios"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
